version: '3.6'
services:  
  elasticsearch:
      container_name: elasticsearch
      restart: always
      ports:
          - '9200:9200'
          - '9300:9300'
      ulimits:
        memlock:
          soft: -1
          hard: -1
      environment:
        - bootstrap.memory_lock=true
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.0'
      network_mode: bridge
     
  kibana-01:
    container_name: kibana-01
    ports:
        - '5601:5601'
    environment:
        - 'ELASTICSEARCH_HOSTS=http://elasticsearch:9200'   
    image: 'docker.elastic.co/kibana/kibana:7.17.0' 
    ulimits:
      memlock:
        soft: -1
        hard: -1
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    network_mode: bridge

  logstash:
    image: logstash:7.17.0
    container_name: logstash
    ports:
      - 5044:5044
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    environment:
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch  
  
    network_mode: bridge

  filebeat:
      user: root
      container_name: filebeat-01

      volumes:
        - ./mylog:/usr/share/filebeat/mylog
        - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
        - "/var/run/docker.sock:/var/run/docker.sock"

      command: filebeat -e -strict.perms=false
      
      image: 'docker.elastic.co/beats/filebeat:7.17.0'
      ulimits:
        memlock:
          soft: -1
          hard: -1
      deploy:
        mode: global
      depends_on:
        - logstash
      network_mode: bridge                   